spring:
  datasource:
    driver-class-name: ${DB_DRIVE}
    url: ${DB_URL}?allowMultiQueries=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      database: ${MONGO_DB}
      uri: ${MONGO_URL}
server:
  port: 8080
